config/routes.rb
Rails.application.routes.draw do
  # root to login page and add button there to 'sign up'
  root 'sessions#new'
  
  get '/profile', to: 'users#profile'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#omniauth' 
  get 'auth/failure', to: redirect('/')
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/alphabetical_venues', to: 'alphabetical_venues#index'

  resources :users

  resources :events, only: [:index, :show, :create, :new, :edit, :destroy]

  # only create an event associated with a venue
  resources :venues do
    resources :events, only: [:index, :show, :create, :new, :edit, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    belongs_to :venue
    validates :title, presence: true
    validates :date, presence: true
    validates :description, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :venues, through: :events
  has_secure_password

  validates :email, presence: true, uniqueness: true, on: :create
  validates :username, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :password_digest, presence: true
 
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :events
    has_many :users, through: :events
    validates :name, presence: true, uniqueness: true
    validates :seating, presence: true, length: { maximum: 20 } 

    def self.alphabetize
        order('name ASC')
    end
end

app/controllers/alphabetical_venues_controller.rb
class AlphabeticalVenuesController < ApplicationController
    def index
        @alphabetical_venues = Venue.alphabetize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

    def welcome
        if !logged_in?
            redirect_to login_path
        end
    end

end

app/controllers/events_controller.rb
  class EventsController < ApplicationController
    before_action :find_event, :find_venue

    def index
      @events = @venue.events
    end

    def new
      @event = Event.new
    end

    def create
      @event = @venue.events.build(event_params)
        if @event.save
            redirect_to venue_events_path(@venue)
        else
            render :new
        end
    end

    def show 
        if @event.blank?
            redirect_to new_user_path
        end  
    end

    def edit
    end

    def update
      if @event.update(event_params)
        redirect_to event_path(@event)
      else
        render :edit
      end
    end

    def destroy
        @event.destroy
        redirect_to events_path
    end 

  private

      def event_params
          params.require(:event).permit(:title, :date, :description, :venue_id, :user_id)
      end

      def find_event
          @event = Event.find_by_id(params[:id])
      end

      def find_venue
          @venue = Venue.find_by(id: params[:venue_id])
      end
      
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        if logged_in?
            redirect_to venues_path
        end
    end
    
    def create
        user = User.find_by_username(params[:username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            render :new
        end
    end

    def omniauth
        user = User.find_or_create_by(uid: request.env['omniauth.auth'][:uid], provider: request.env['omniauth.auth'][:provider]) do |u|
            u.email = request.env['omniauth.auth'][:info][:email]
            u.username = request.env['omniauth.auth'][:info][:name]
            u.password = SecureRandom.hex(15)
        end
        if user.valid?
            session[:user_id] = user.id
            redirect_to root_path
        else
            redirect_to login_path
        end
    end

    def destroy
        session.clear
        redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include ApplicationHelper

    def index
        @users = User.all
    end

    def new 
        if !logged_in?
            @user = User.new 
        else
            redirect_to root_path
        end 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            render :new
        end 
    end 

    def show
        @user = User.find_by_id(params[:id])
        if @user.blank?
            redirect_to new_user_path
        end
    end

    def edit
        @user = User.find_by_id(params[:id])
    end

    def update 
        if @user.update(user_params)
            redirect_to user_path(@user)
        else 
            render :edit
        end 
    end 

    def profile
        redirect_to user_path(current_user)
    end

    def destroy
        @user = User.find_by_id(params[:id])
        @user.destroy
        redirect_to users_path
    end 

private

def user_params
    params.require(:user).permit(:name, :email, :username, :password)
end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

    def index
        @venues = Venue.all
        @event = Event.all
    end

    def new
        @venue = Venue.new
        @venue.events.build
    end

    def create
        if @event
            @venue = @event.venues.build(venue_params)
        else 
            @venue = Venue.new(venue_params)
        end

        if @venue.save
            redirect_to venue_path(@venue)
        else
            render :new
        end
    end

    def show
        @event = Event.find_by_id(params[:id])
        @venue = Venue.find_by_id(params[:venue_id])
        if @venue.blank?
            redirect_to venues_path
        end
    end

private

    def venue_params
        params.require(:venue).permit(:name, :seating)
    end
    
end

app/helpers/alphabetical_venues_helper.rb
module AlphabeticalVenuesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

 
    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

    def logged_in?
        !!session[:user_id]
    end

end

app/helpers/events_helper.rb
module EventsHelper
    def event_count(venue)
        Venue.find_by_id(venue.id).events.count
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/alphabetical_venues/_buttons.html.erb
<div class="button">
    <%= button_to "Venues", venues_path, method: :get %><br>
    
    <% if current_user %>
        <%= button_to "Profile",'/profile', method: :get %><br>
    <% end %>
    
    <% if current_user %>
        <%= button_to 'Logout', logout_path %><br>
    <% end %>

</div>

app/views/alphabetical_venues/index.html.erb
<h1>Alphabetical Venues</h1>

<div>
    <ul>
        <% @alphabetical_venues.each do |a| %>
            <li><%= a.name %></li>
        <% end %>
    </ul>
</div>

<%= render partial: "buttons" %>
        

app/views/application/welcome.html.erb
<h1>Welcome Page!</h1>

<%= button_to 'Logout', logout_path %>

app/views/events/_buttons.html.erb
<div class="button">
    <%= button_to 'Logout', logout_path %><br>
    <%= button_to "Venues", venues_path, method: :get %><br>
        <% if current_user %>
        <%= button_to "Profile", '/profile', method: :get %><br>
    <% end %>
</div>

app/views/events/edit.html.erb
<h1>Events#new</h1>

<%= form_with model: [@venue, @event] do |f| %>
  <% if @user.errors.any? %>
      <div id="error_explanation">
    <h2>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being saved:
    </h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :venue_id, value: @venue.id %>
    
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <br>
    <%= f.label :date %>
    <%= f.datetime_field :date %>
    <br>
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br>
    <br>

    <%= f.submit "Create Event" %>
<% end %>

<%= render partial "buttons" %>

app/views/events/index.html.erb
<h1>Events#index</h1>


<h3><%= pluralize(event_count(@venue), "Event(s) to show for #{@venue.name}") %></h3>
<h4>Click on an event for more information: </h4>
<ul>
    <% @events.each do |e| %>
        <% if @venue.id == e.venue_id %>
        <li><strong><%= link_to e.title, venue_event_path(@venue, e) %></strong></li>
    <% end %> 
<% end %>
</ul>

<%= button_to "Add Event to this Venue", new_venue_event_path(@venue), method: :get %>
<br>


<%= render partial: "buttons" %>

app/views/events/new.html.erb
<h1>Events#new</h1>

<%= form_with model: [@venue, @event] do |f| %>
  <% if @event.errors.any? %>
      <div id="error_explanation">
    <h2>
      <%= pluralize(@event.errors.count, "error") %>
      prohibited this event from being saved:
    </h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :venue_id, value: @venue.id %>
    
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <br>
    <%= f.label :date %>
    <%= f.datetime_field :date %>
    <br>
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br>
    <br>

    <%= f.submit "Create Event" %>
<% end %>

<%= button_to "Venues", venues_path, method: :get %><br>

<%= render partial: "buttons" %>

app/views/events/show.html.erb
<h1>Events#show</h1>

<h3><%= @event.title %></h3>
<strong><%= @event.date %></strong>
<strong><%= @event.description %></strong>


<%= render partial: "buttons" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HereToHear1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>Hear To Hear</h1>
    <%= yield %>
  </body>
</html>

app/views/users/_buttons.html.erb
<div class="button">
    <% if current_user %>
    <%= button_to "Profile",    '/profile', method: :get %><br>
    <% end %>
    <%= button_to "Venues",    venues_path, method: :get %><br>
</div>

app/views/users/edit.html.erb
<h1>Edit#Users</h1>


<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %> 

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

  <!-- <%= f.hidden_field(:user_id, value: "1") %> -->
  <!-- <input type="hidden" name="user[user_id]" value="1"> -->

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Here:</h1>

<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

  
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

  <%= f.submit 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<h1>Users#Show</h2>

<ul>
    <li>Username: <%= @user.username %></li>
    <li>Email: <%= @user.email %></li>
</ul>
<%= render partial: "buttons" %>

app/views/venues/_buttons.html.erb
<div class="button">
    
    <%= button_to "Create new Venue", new_venue_path, method: :get %><br>
    <%= button_to 'Alphabetical Venues', '/alphabetical_venues', method: :get%><br>
    <% if logged_in? %>
        <%= button_to "Profile",'/profile', method: :get %><br>
        <%= button_to 'Logout', logout_path %><br>
    <% else %>
        <%= button_to 'Login', login_path %>
    <% end %>
</div>

app/views/venues/index.html.erb
<h1>Venues</h1>

<br>

<h3><%= pluralize(@venues.count, 'Venue') %></h3>
<br>
<h3>Click On A Venue to See Events!</h3>

<ul>
    <% @venues.each do |v| %>
        <li><strong><%= link_to v.name, venue_events_path(v, @events) %></strong></li>
    <% end %>
</ul>

<%= render partial: "buttons" %>

app/views/venues/new.html.erb
<h1>Venues#new</h1>

<%= form_with model: @venue do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
        <%= f.label :seating %>
    <%= f.text_field :seating %>
    <br>
    <br>
    <%= f.submit "Create Venue" %>
<% end %>
<br>

<%= button_to "Venues", venues_path, method: :get %><br>

<%= render partial: "buttons" %>

app/views/venues/show.html.erb
<h1>Venues#show</h1>

Name: <strong><%= @venue.name %></strong>